## Домашнее задание: библиотека Numpy

In [9]:
import numpy as np
import random
import scipy.stats as sps

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
import random
import numpy as np
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
print("NDIM a: ", a.ndim, " b: ", b.ndim)
print("SHAPE a: ", a.shape, " b: ", b.shape)
# ========
print(a)
print(b)

NDIM a:  2  b:  2
SHAPE a:  (100, 100)  b:  (100, 100)
[[0.6718568  0.60302309 0.68989439 ... 0.5891228  0.79884881 0.95092443]
 [0.17036914 0.00792639 0.43551828 ... 0.71013201 0.83840255 0.75547414]
 [0.80765981 0.9732272  0.18089256 ... 0.50340671 0.40968215 0.54204773]
 ...
 [0.34858597 0.2083309  0.66299936 ... 0.26650728 0.65138907 0.07820485]
 [0.41055044 0.28573371 0.76937681 ... 0.62427248 0.43618679 0.0203975 ]
 [0.4263967  0.3806674  0.55322395 ... 0.00684745 0.86224138 0.81920918]]
[[0.57432459 0.67186938 0.93536107 ... 0.24544618 0.90966882 0.0021505 ]
 [0.74005688 0.49322812 0.38317954 ... 0.28674886 0.9597672  0.81509281]
 [0.92860303 0.87815376 0.09170984 ... 0.49537086 0.77204314 0.65615601]
 ...
 [0.02359686 0.59726894 0.21385061 ... 0.34338338 0.5693192  0.01878154]
 [0.80747638 0.54929141 0.44261988 ... 0.45524617 0.663235   0.29644505]
 [0.66782769 0.00668757 0.5646831  ... 0.04073926 0.14753933 0.04920865]]


In [ ]:
def mult(a, b):
    """
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    #pass
    l = len(a)
    c = [[sum(a[i][n] * b[n][j] for n in range(l)) for j in range(l)] for i in range(l)]
    return c

print(mult(a, b))

[[26.386742765595613, 24.690796075873312, 27.14099913409862, 27.000833424572697, 24.004035238754433, 24.710025053012064, 27.641749241783394, 26.68831373063, 28.744671833400947, 25.75747953547604, 26.822180171468144, 22.645302321525982, 27.023803750838354, 24.402836957194722, 24.863248818752247, 25.175673654506557, 24.294595406375056, 25.507763128445013, 26.911494356679516, 26.3467450902248, 28.803115860842883, 20.385179746500324, 22.762690694834582, 24.14792673715911, 25.162471749322766, 27.132053874749882, 24.724358023625985, 22.62836257994447, 26.52267451238544, 25.077634584017737, 26.17284459256475, 26.198966063084907, 27.028189552498425, 24.180381715178896, 27.270528442249667, 29.16475488388721, 28.266445963519143, 24.811516651216216, 24.773832039201906, 29.096086628322777, 26.570838137968753, 25.76050141756213, 21.860269606727748, 26.921045463869977, 25.406604913025085, 23.66503866286166, 26.34177036300148, 25.16273880990416, 26.575952469387897, 24.954577377604746, 24.608865409864

In [ ]:
def np_mult(a, b):
    """
    a: np.array[size, size]             --- первая матрица-аргумент
    b: np.array[size, size] --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b

    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    #pass
    c = a @ b
    return c

print(np_mult(a, b))


[[26.38674277 24.69079608 27.14099913 ... 27.43400079 25.80831423
  26.41821524]
 [25.68112137 25.65483465 27.22786758 ... 28.27822998 24.71292339
  24.75200842]
 [22.10465814 22.32870682 23.95345512 ... 24.24382684 22.61176411
  21.61891652]
 ...
 [23.01605639 22.32728455 24.78597021 ... 25.27788305 23.21021015
  23.13945899]
 [26.4856828  25.93231466 27.26031472 ... 28.17403671 26.73204555
  25.92566542]
 [23.13953301 21.35735931 22.59689139 ... 24.52093689 23.54598666
  21.57843885]]


In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.25 s, sys: 453 µs, total: 1.25 s
Wall time: 1.32 s


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.72 ms, sys: 4.07 ms, total: 5.79 ms
Wall time: 5.53 ms


In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)
print(np.allclose(np.array(M1), M2))

True


### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве.

Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без.

Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.79883595 0.3303067  0.02555681] [0.11565263 0.57992854 0.95416226]


In [ ]:
def scalar_product(a, b):
    """
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """
    #pass
    c = 0
    for x, y in zip(a, b):
        c = c + x * y
    return c

print(scalar_product(a, b))

0.30832710491856913


In [ ]:
def np_scalar_product(a,b):
    """
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """
    #pass
    c = a.dot(b)
    return c

print(np_scalar_product(a,b))

0.30832710491856913


In [ ]:
%time
product_1 = scalar_product(a,b)
%time
product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)
print(np.allclose(product_1, product_2))

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.2 µs
CPU times: user 1 µs, sys: 1 µs, total: 2 µs
Wall time: 4.53 µs
True


Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`. Используйте библиотеку Numpy

In [ ]:
def np_diag_2k(a):
    """
    a: np.array[m, m] --- первая матрица-аргумент
    return c: float   --- сумма элементов массива а, принадлежащих диагонали и являющимися четными

    Функция принимает на вход квадратную матрицу размерностью m x m и возвращает число,
    равное сумме четных диагональных элементов этой квадратной матрицы

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    c = np.diag(a)
    c = c[c%2==0].sum()
    return c
    #pass

#a = np.random.randint(1, 10, size=(5, 5))

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
print(a)
print(np_diag_2k(a))

[[6 5 8 2 7]
 [8 5 4 1 4]
 [9 9 2 6 8]
 [2 8 1 3 7]
 [9 9 6 7 3]]
8


In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 128 µs, sys: 16 µs, total: 144 µs
Wall time: 156 µs


8

### Задание 4
​
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $(x = (x_1, x_2, \ldots, x_n)$ массива $X$ строит строчку $s = (s_1, s_2, \ldots, s_n)$,  где $s_k=x_1+...+x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку <code>numpy</code> (вам поможет функция <code>cumsum</code>). Выходом функции должен быть двумерный <code>numpy</code>-массив той же формы, что и $X$.
​

In [ ]:
def cumsum(A):
    """
    A: np.array[num_row, num_column]        --- матрица-аргумент
    return S: np.array[num_row, num_column] --- выходная матрица кумулятивных сумм

    Функция принимает на вход матрицу A размерностью n x m и возвращает
    матрицу с той же размерностью n x m, i-ая строчка которой есть последовательность
    кумулятивных сумм элементов i-ой строки матрицы A

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    S = np.cumsum(A, axis=1)
    return S
    #pass
print(cumsum(np.array([[1,2,3],[4,5,6]])))

[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
# зададим некоторую последовательность и проверим ее на вашей функции.
A = sps.uniform.rvs(size=(2, 10**3))
print(A)
%time S2 = cumsum(A)

[[0.78907248 0.46225834 0.87065823 ... 0.83535867 0.2484679  0.76332348]
 [0.29541928 0.33398753 0.29501775 ... 0.30958345 0.19113412 0.69442874]]
CPU times: user 51 µs, sys: 6 µs, total: 57 µs
Wall time: 60.8 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив x с преобразованным x и вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [67]:
from copy import copy
def np_transformation(X, a=1):
    """
    X: np.array[num_row, num_column]          --- матрица-аргумент
    a: float                                  --- значение для преобразования нечетных элементов строк в X
    return S: np.array[num_row, num_column*2] --- матрица, где строки являются
    сконкатенированными строками изначальной матрицы X со строками, являющимися их преобразованиями

    Функция принимает на вход матрицу X размерностью n x m, число a и
    возвращает  матрицу с размерностью n x m*2, i-ая строчка которой является склеенной
    i-ой строкой X с ее преобразованием ее строки transformation(X[i]), записанном в обратном порядке,
    где преобразование для числа k определено как:
    transformation(k) = a if ind(k) % 2 == 0 else k**3

    В реализации этой функции необходимо использовать функционал пакета numpy

    """
    #pass
    X1 = X.copy()
    #S = np.array(X1, dtype=np.int64)
    S = []
    for i in range(X1.shape[0]):
      X1[i][::2]=X1[i][::2]**3
      X1[i][1::2]=[a for j in X1[i][1::2]]
      row = np.append(X[i], np.flip(X1[i]), axis=0)
      S.append(row)
    #S = np.append([X, X1])
    return np.array(S)
print(np.array2string(np_transformation(np.array([[100,200,300,400,500]])), separator=', '))

[[      100,       200,       300,       400,       500, 125000000,
          1,  27000000,         1,   1000000]]


In [56]:
X = np.array([[i for i in range(1, 10, 2)]])
%time S2 = np_transformation(X, 5)

CPU times: user 1.17 ms, sys: 0 ns, total: 1.17 ms
Wall time: 1.12 ms
